services:

  mc-router:
      image: itzg/mc-router
      container_name: mc-router
      restart: unless-stopped
      ports:
        - "25565:25565"
      environment:
        # Format: domain=container_name:port
        - MAPPING=<yourdomain.com>=minecraft-server:25565,<yourdomain2.com>=minecraft-server2:25565 # <-- Replace <yourdomain.com> with your actual domain
      networks:
        - minecraft-network

# Minecraft Server
# Using Java 25 for newer JVM arguments, and Fabric for modding
  server:
    image: itzg/minecraft-server:java25-graalvm
    container_name: minecraft-server
    stdin_open: true
    tty: true
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    # The entrypoint script is to bind the Minecraft server to the CPU and Memory of NUMA node 0, which can help improve performance on multi CPUs setups.
    entrypoint: >
      bash -c "
      microdnf install -y numactl-libs numactl &&
      CPUS=$$(numactl -H | grep 'node 0 cpus' | cut -d: -f2 | awk '{$1=$1;print}' | sed 's/ /,/g') &&
      echo 'Detected Node 0 CPUs: '$$CPUS &&
      exec numactl --physcpubind=$$CPUS --membind=0 /start
      "
    stop_grace_period: 1m
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.11"
      FABRIC_VERSION: "0.18.5"
      MEMORY: "10G" # <-- Adjust this based on your server's available RAM
      JVM_OPTS: >
        --add-modules=jdk.incubator.vector
        -XX:+UseZGC
        -XX:-ZProactive
        -XX:SoftMaxHeapSize=28G
        -XX:+UnlockExperimentalVMOptions
        -XX:+UnlockDiagnosticVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:+UseNUMA
        -XX:+PerfDisableSharedMem
        -XX:-DontCompileHugeMethods
        -XX:MaxNodeLimit=240000
        -XX:NodeLimitFudgeFactor=8000
        -XX:ReservedCodeCacheSize=400M
        -XX:NonNMethodCodeHeapSize=12M
        -XX:ProfiledCodeHeapSize=194M
        -XX:NonProfiledCodeHeapSize=194M
        -XX:NmethodSweepActivity=1
        -XX:+UseFastUnorderedTimeStamps
        -XX:+UseCriticalJavaThreadPriority
        -XX:AllocatePrefetchStyle=1
        -XX:+AlwaysActAsServerClassMachine
        -XX:+UseTransparentHugePages
        -XX:LargePageSizeInBytes=2M
        -XX:+UseLargePages
        -XX:+EagerJVMCI
        -XX:+UseStringDeduplication
        -XX:+UseAES
        -XX:+UseAESIntrinsics
        -XX:+UseFMA
        -XX:+UseLoopPredicate
        -XX:+RangeCheckElimination
        -XX:+OptimizeStringConcat
        -XX:+UseCompressedOops
        -XX:+UseThreadPriorities
        -XX:+OmitStackTraceInFastThrow
        -XX:+RewriteBytecodes
        -XX:+RewriteFrequentPairs
        -XX:+UseFPUForSpilling
        -XX:+UseFastStosb
        -XX:+UseNewLongLShift
        -XX:+UseVectorCmov
        -XX:+UseXMMForArrayCopy
        -XX:+UseXmmI2D
        -XX:+UseXmmI2F
        -XX:+UseXmmLoadAndClearUpper
        -XX:+UseXmmRegToRegMoveAll
        -XX:+EliminateLocks
        -XX:+DoEscapeAnalysis
        -XX:+AlignVector
        -XX:+OptimizeFill
        -XX:+EnableVectorSupport
        -XX:+UseCharacterCompareIntrinsics
        -XX:+UseCopySignIntrinsic
        -XX:+UseVectorStubs
        -XX:UseAVX=2
        -XX:UseSSE=4
        -XX:+UseFastJNIAccessors
        -XX:+UseInlineCaches
        -XX:+SegmentedCodeCache
        -Djdk.nio.maxCachedBufferSize=262144
        -Djdk.graal.UsePriorityInlining=true
        -Djdk.graal.Vectorization=true
        -Djdk.graal.OptDuplication=true
        -Djdk.graal.DetectInvertedLoopsAsCounted=true
        -Djdk.graal.LoopInversion=true
        -Djdk.graal.VectorizeHashes=true
        -Djdk.graal.EnterprisePartialUnroll=true
        -Djdk.graal.VectorizeSIMD=true
        -Djdk.graal.StripMineNonCountedLoops=true
        -Djdk.graal.SpeculativeGuardMovement=true
        -Djdk.graal.TuneInlinerExploration=1
        -Djdk.graal.LoopRotation=true
        -Djdk.graal.CompilerConfiguration=enterprise
    volumes:
      - ./serverdata:/data
    networks:
      - minecraft-network

# Miniserve: A simple and efficient file server for sharing files over HTTP.
# for sharing modpack, configs, and other files related to the Minecraft server.
  miniserve:
    image: svenstaro/miniserve:latesta
    container_name: miniserve
    restart: unless-stopped
    volumes:
      - ./data:/data
    command: -v --enable-tar --enable-zip /data
    networks:
      - file-network

# Anubis
# A lightweight reverse proxy and bot mitigation tool to protect the Miniserve file server from malicious bots and crawlers.
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    restart: unless-stopped
    environment:
      - BIND=:8923
      - TARGET=http://miniserve:8080
      - POLICY_FNAME=/data/cfg/botPolicy.yaml
    volumes:
      - ./botPolicy.yaml:/data/cfg/botPolicy.yaml:ro
    networks:
      - file-network
    depends_on:
      - miniserve

# Nginx Proxy Manager
# for managing reverse proxies, SSL certificates, and access control for the Minecraft server and Miniserve.
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - file-network

# DDNS Client for DuckDNS
# keeps your dynamic IP address updated with DuckDNS Domain
# using DuckDNS because you get 5 free domains and easy to set up
  ddns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: ddns
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin # <-- Set your timezone
      - SUBDOMAINS=<DUCKDNS_SUBDOMAIN> # <-- Your DuckDNS subdomain (without .duckdns.org)
      - TOKEN=<DUCKDNS_TOKEN> # <-- Your DuckDNS token
      - PUID=1000
      - PGID=1000

networks:
  minecraft-network:
    external: false
  file-network:
    external: false